name: Deploy to Scalingo

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - uses: scalingo-community/setup-scalingo@v0.1.1
      with:
        region: 'osc-fr1'
        api_token: ${{ secrets.scalingo_api_token }}
        app_name: 'bbossnycmn'

    - run: scalingo restart # will restart all the processes of the app "bbossnycmn" in region "osc-fr1"
