name: Deploy to Scalingo

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Configure Scalingo CLI
        uses: scalingo-community/setup-scalingo@v0.1.1
        with:
          api_token: ${{ secrets.SCALINGO_API_TOKEN }}
          region: 'osc-fr1'
          app_name: 'my_app'
          
      - name: Deploy to Scalingo with Git
        run: git push scalingo main
